# Size
- name: size/XS
  color: "009900"
  description: >-
    Denotes a PR that changes 0-9 lines, ignoring generated files.
- name: size/S
  color: "77bb00"
  description: >-
    Denotes a PR that changes 10-29 lines, ignoring generated files.
- name: size/M
  color: "eebb00"
  description: >-
    Denotes a PR that changes 30-99 lines, ignoring generated files.
- name: size/L
  color: "ee9900"
  description: >-
    Denotes a PR that changes 100-499 lines, ignoring generated files.
- name: size/XL
  color: "ee5500"
  description: >-
    Denotes a PR that changes 500-999 lines, ignoring generated files.
- name: size/XXL
  color: "ee0000"
  description: >-
    Denotes a PR that changes 1000+ lines, ignoring generated files.
# Uncategorized
- name: link-checker
  color: "7B55D7"