---
name: Link Checker

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.3.2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args:  --no-progress --exclude-all-private
          format: markdown
      - name: Find Link Checker Issue
        id: link-checker-issue
        uses: micalevisk/last-issue-action@v1
        with:
          state: open
          labels: |
            link-checker
      - name: Update Issue
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Broken links detected in docs 🔗
          issue-number: "${{ steps.link-checker-issue.outputs.issue_number }}"
          content-filepath: ./lychee/out.md
          token: ${{secrets.GITHUB_TOKEN}}
          labels: |
            link-checker
