---
name: Link Checker

on:
  push:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.3.2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Find Link Checker Issue
        id: link-checker-issue
        uses: micalevisk/last-issue-action@v1
        with:
          state: open
          labels: |
            link-checker
      - name: Update Issue
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Broken links detected in docs 🔗
          issue-number: "${{ steps.link-checker-issue.outputs.issue_number }}"
          content-filepath: ./lychee.md
          token: ${{secrets.GITHUB_TOKEN}}
          labels: |
            link-checker
