---
name: MegaLinter

on: # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: MegaLinter
        uses: megalinter/megalinter/flavors/documentation@v5
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          ENABLE_LINTERS: MARKDOWN_MARKDOWNLINT,ACTION_ACTIONLINT,DOCKERFILE_HADOLINT,GIT_GIT_DIFF,JSON_JSONLINT,MARKDOWN_MARKDOWN_TABLE_FORMATTER,SPELL_MISSPELL,CREDENTIALS_SECRETLINT
          VALIDATE_ALL_CODEBASE: true
          PRINT_ALPACA: false
          MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yaml
      - name: Archive production artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: MegaLinter reports
          path: |
            report
            mega-linter.log
